#!/bin/sh

# Signal 2
#!/bin/sh

# Prints the current volume or 🔇 if muted.
case $BLOCK_BUTTON in
	2) setsid -f "$TERMINAL" -e pulsemixer ;;
	1) wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle ;;
	4) wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ && echo 󰝝 ;;
	5) wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && echo 󰝞 ;;
	3) notify-send "Volume module" "\- Shows volume 󰖀, 󰝟 if muted.
- Left click to mute.
- Middle click to toggle.
- Scroll to change." ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

wp="$(wpctl get-volume @DEFAULT_AUDIO_SINK@)"
vol="$(echo $wp | awk '{print $2}')" && icon=󱄠

ismuted="$(echo "$wp" | awk '{print $3}')"

[ -n "$ismuted" ] && icon=

echo "$icon$vol"
